#!/usr/bin/env bash

# Create Bazel cache volume
docker volume create bazel-cache

# Check if base container exists
docker inspect base &> /dev/null

if [[ $? -ne 0 ]]; then
  echo "Bazel server container does not exist, creating."
  docker run \
    --name base \
    --rm \
    -d \
    -v "/var/lib/buildkite-agent/builds:/var/lib/buildkite-agent/builds" \
    -v "/usr/local/bin/buildkite-agent:/usr/local/bin/buildkite-agent" \
    -v "bazel-cache:/root/.cache/bazel" \
    --init \
    --entrypoint tail \
    buildpack-deps:buster@sha256:cbf9915fc2c12f95de45033fd6c1131cdbfbc35ce12bf6a6b1dc76a55d9f011a \
    -f /dev/null
fi

echo "Starting Bazel server for $BUILDKITE_BUILD_CHECKOUT_PATH."
docker exec \
  -w $BUILDKITE_BUILD_CHECKOUT_PATH \
  base \
  ./start-bazel.sh
